### Using Hidden Layer to decrease loss for our iris separation


In [15]:
import tensorflow as tf
import pandas as pd

# data prepare

location = 'C:/Users/woner/Desktop/coding/machine_learning/(me)life_coding_Tensorflow101/csv/iris.csv'
iris = pd.read_csv(location)

# One hot encoding because classification
iris = pd.get_dummies(iris)
print(iris.columns)
# variable
independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor',
       '품종_virginica']]

# model structure with hidden layer
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics = 'accuracy')

# Fit

model.fit(independent,dependent,epochs=100,verbose=0)

# Test

print(model.predict(independent[0:5]))
print(dependent[0:5])

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
[[9.9998796e-01 1.1347693e-05 7.0092455e-07]
 [9.9991560e-01 8.1384627e-05 2.9700575e-06]
 [9.9997461e-01 2.3586630e-05 1.8114538e-06]
 [9.9991381e-01 8.1604659e-05 4.5844545e-06]
 [9.9999142e-01 7.9299671e-06 6.4713652e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
